behaviors:
  Dinosaur Agent:
    trainer_type: sac
    hyperparameters:
      learning_rate: 0.0003
      learning_rate_schedule: constant
      batch_size: 250
      buffer_size: 500000
      buffer_init_steps: 0
      tau: 0.01
      steps_per_update: 20.0
      save_replay_buffer: false
      init_entcoef: 1.0
      reward_signal_steps_per_update: 20.0
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 3  
      vis_encode_type: resnet    
    reward_signals:
      extrinsic:        
        strength: 1.0       
    keep_checkpoints: 20
    checkpoint_interval: 50000
    max_steps: 1e6
    time_horizon: 2000
    summary_freq: 10000           
engine_settings:
  time_scale: 1
  width: 96
  height: 54
env_settings:
  env_path: Builds\DinosaurioCamHard\DinosaurioAI
  num_envs: 5
torch_settings:
  device: cuda:0