default_settings: null
behaviors:
  Dinosaur Agent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2024
      buffer_size: 20240
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 512
      num_layers: 3      
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0
    keep_checkpoints: 20
    checkpoint_interval: 50000
    max_steps: 7000000
    time_horizon: 2000
    summary_freq: 10000        
engine_settings:
  time_scale: 1
  width: 96
  height: 54
env_settings:
  env_path: Builds\DinosaurioRayEntrenamiento\DinosaurioAI
  num_envs: 10
torch_settings:
  device: cuda:0